return class WordGame {
    constructor(display) {

        //516th element is "2022-11-04"'s word
        this.dailyAnswers = [
            "rebut",
            "rebut",
            "rebut",
            "humph",
            "awake",
            "blush",
            "focal",
            "evade",
            "naval",
            "serve",
            "heath",
            "heath",
            "model",
            "karma",
            "karma",
            "grade",
            "quiet",
            "bench",
            "abate",
            "feign",
            "major",
            "death",
            "fresh",
            "crust",
            "crust",
            "abase",
            "abase",
            "marry",
            "react",
            "batty",
            "pride",
            "floss",
            "helix",
            "croak",
            "staff",
            "paper",
            "unfed",
            "whelp",
            "trawl",
            "outdo",
            "adobe",
            "crazy",
            "sower",
            "repay",
            "digit",
            "crate",
            "cluck",
            "spike",
            "mimic",
            "mimic",
            "maxim",
            "linen",
            "unmet",
            "flesh",
            "flesh",
            "forth",
            "first",
            "stand",
            "belly",
            "ivory",
            "ivory",
            "print",
            "yearn",
            "drain",
            "bribe",
            "stout",
            "panel",
            "crass",
            "flume",
            "offal",
            "agree",
            "error",
            "swirl",
            "argue",
            "bleed",
            "delta",
            "flick",
            "totem",
            "totem",
            "front",
            "shrub",
            "parry",
            "biome",
            "lapel",
            "start",
            "greet",
            "goner",
            "golem",
            "golem",
            "loopy",
            "round",
            "audit",
            "lying",
            "gamma",
            "labor",
            "islet",
            "civic",
            "forge",
            "corny",
            "moult",
            "basic",
            "salad",
            "agate",
            "spicy",
            "spray",
            "essay",
            "fjord",
            "spend",
            "kebab",
            "guild",
            "aback",
            "motor",
            "alone",
            "hatch",
            "hyper",
            "thumb",
            "thumb",
            "ought",
            "ought",
            "dutch",
            "pilot",
            "tweed",
            "comet",
            "jaunt",
            "jaunt",
            "steed",
            "abyss",
            "growl",
            "fling",
            "dozen",
            "dozen",
            "erode",
            "world",
            "gouge",
            "click",
            "briar",
            "great",
            "altar",
            "pulpy",
            "blurt",
            "coast",
            "duchy",
            "duchy",
            "fixer",
            "group",
            "rogue",
            "badly",
            "smart",
            "pithy",
            "gaudy",
            "chill",
            "heron",
            "heron",
            "finer",
            "surer",
            "radio",
            "rouge",
            "perch",
            "perch",
            "wrote",
            "clock",
            "tilde",
            "store",
            "prove",
            "bring",
            "solve",
            "cheat",
            "grime",
            "exult",
            "usher",
            "epoch",
            "triad",
            "break",
            "rhino",
            "viral",
            "conic",
            "masse",
            "sonic",
            "vital",
            "trace",
            "using",
            "peach",
            "champ",
            "baton",
            "brake",
            "pluck",
            "craze",
            "gripe",
            "weary",
            "picky",
            "acute",
            "ferry",
            "aside",
            "tapir",
            "troll",
            "unify",
            "rebus",
            "boost",
            "truss",
            "siege",
            "tiger",
            "tiger",
            "slump",
            "crank",
            "gorge",
            "query",
            "drink",
            "favor",
            "abbey",
            "tangy",
            "panic",
            "solar",
            "shire",
            "proxy",
            "point",
            "robot",
            "robot",
            "wince",
            "crimp",
            "knoll",
            "sugar",
            "whack",
            "whack",
            "whack",
            "could",
            "wrung",
            "light",
            "those",
            "those",
            "shard",
            "pleat",
            "aloft",
            "skill",
            "elder",
            "frame",
            "humor",
            "pause",
            "ulcer",
            "ultra",
            "robin",
            "cynic",
            "aroma",
            "caulk",
            "shake",
            "dodge",
            "swill",
            "tacit",
            "other",
            "thorn",
            "trove",
            "bloke",
            "vivid",
            "spill",
            "chant",
            "choke",
            "rupee",
            "nasty",
            "mourn",
            "ahead",
            "brine",
            "cloth",
            "hoard",
            "sweet",
            "month",
            "lapse",
            "watch",
            "today",
            "focus",
            "smelt",
            "tease",
            "cater",
            "movie",
            "saute",
            "allow",
            "renew",
            "their",
            "slosh",
            "purge",
            "chest",
            "depot",
            "epoxy",
            "epoxy",
            "found",
            "shall",
            "harry",
            "stove",
            "lowly",
            "snout",
            "trope",
            "fewer",
            "shawl",
            "natal",
            "comma",
            "foray",
            "scare",
            "stair",
            "stair",
            "squad",
            "royal",
            "chunk",
            "mince",
            "shame",
            "cheek",
            "ample",
            "flair",
            "foyer",
            "cargo",
            "oxide",
            "plant",
            "olive",
            "inert",
            "askew",
            "heist",
            "shown",
            "zesty",
            "hasty",
            "trash",
            "fella",
            "larva",
            "forgo",
            "story",
            "hairy",
            "train",
            "homer",
            "badge",
            "midst",
            "canny",
            "canny",
            "butch",
            "farce",
            "slung",
            "tipsy",
            "metal",
            "yield",
            "delve",
            "being",
            "scour",
            "glass",
            "gamer",
            "scrap",
            "money",
            "hinge",
            "album",
            "vouch",
            "asset",
            "tiara",
            "crept",
            "bayou",
            "atoll",
            "manor",
            "creak",
            "showy",
            "phase",
            "phase",
            "depth",
            "gloom",
            "flood",
            "trait",
            "trait",
            "piety",
            "payer",
            "goose",
            "float",
            "donor",
            "atone",
            "primo",
            "apron",
            "apron",
            "cacao",
            "loser",
            "input",
            "gloat",
            "awful",
            "brink",
            "smite",
            "beady",
            "rusty",
            "retro",
            "droll",
            "droll",
            "hutch",
            "pinto",
            "gaily",
            "egret",
            "lilac",
            "sever",
            "field",
            "fluff",
            "hydro",
            "flack",
            "agape",
            "voice",
            "stead",
            "stalk",
            "berth",
            "madam",
            "night",
            "bland",
            "liver",
            "wedge",
            "augur",
            "roomy",
            "wacky",
            "flock",
            "angry",
            "bobby",
            "trite",
            "aphid",
            "tryst",
            "midge",
            "power",
            "elope",
            "elope",
            "motto",
            "stomp",
            "upset",
            "bluff",
            "cramp",
            "quart",
            "coyly",
            "youth",
            "rhyme",
            "buggy",
            "alien",
            "alien",
            "unfit",
            "patty",
            "cling",
            "glean",
            "label",
            "hunky",
            "hunky",
            "poker",
            "gruel",
            "twice",
            "twang",
            "shrug",
            "treat",
            "unlit",
            "waste",
            "merit",
            "woven",
            "octal",
            "needy",
            "clown",
            "widow",
            "irony",
            "ruder",
            "gauze",
            "chief",
            "onset",
            "prize",
            "fungi",
            "charm",
            "gully",
            "inter",
            "whoop",
            "taunt",
            "leery",
            "class",
            "theme",
            "lofty",
            "tibia",
            "tibia",
            "alpha",
            "thyme",
            "eclat",
            "doubt",
            "parer",
            "chute",
            "stick",
            "trice",
            "alike",
            "sooth",
            "recap",
            "saint",
            "liege",
            "glory",
            "grate",
            "admit",
            "brisk",
            "brisk",
            "usurp",
            "scald",
            "scorn",
            "leave",
            "twine",
            "sting",
            "bough",
            "marsh",
            "sloth",
            "dandy",
            "vigor",
            "howdy",
            "enjoy",
            "valid",
            "ionic",
            "equal",
            "unset",
            "floor",
            "catch",
            "spade",
            "spade",
            "exist",
            "quirk",
            "denim",
            "grove",
            "spiel",
            "spiel",
            "fault",
            "foggy",
            "flout",
            "carry",
            "sneak",
            "libel",
            "waltz",
            "aptly",
            "piney",
            "piney",
            "aloud",
            "photo",
            "dream",
            "stale",
            "stale",
            "ombre",
            "ombre",
            "unite",
            "snarl",
            "baker",
            "there",
            "glyph",
            "glyph",
            "glyph",
            "spell",
            "folly",
            "louse",
            "louse",
            "vault",
            "godly",
            "threw",
            "fleet",
            "grave",
            "inane",
            "shock",
            "crave",
            "spite",
            "valve",
            "skimp",
            "claim",
            "rainy",
            "rainy",
            "pique",
            "pique",
            "quasi",
            "arise",
            "arise",
            "valet",
            "valet",
            "avert",
            "avert",
            "recut",
            "mulch",
            "genre",
            "plume",
            "plume",
            "count",
            "incur",
            "total",
            "wrest",
            "mocha",
            "deter",
            "study",
            "study",
            "safer",
            "rivet",
            "funny",
            "funny",
            "mound",
            "undue",
            "sedan",
            "sedan",
            "sedan",
            "guile",
            "gusty",
            "equip",
            "tough",
            "canoe",
            "chaos",
            "covet",
            "human",
            "human",
            "lunch",
            "blast",
            "stray",
            "stray",
            "melee",
            "lefty",
            "quick",
            "paste",
            "given",
            "octet",
            "risen",
            "risen",
            "risen",
            "risen",
            "carve",
            "loose",
            "sadly",
            "spilt",
            "apple",
            "slack",
            "honey",
            "final",
            "sheen",
            "eerie",
            "minty",
            "minty",
            "derby",
            "wharf",
            "spelt",
            "coach",
            "erupt",
            "singe",
            "price",
            "spawn",
            "fairy",
            "jiffy",
            "filmy",
            "stack",
            "chose",
            "sleep",
            "ardor",
            "ardor",
            "niece",
            "woozy",
            "handy",
            "grace",
            "ditto",
            "ditto",
            "ditto",
            "usual",
            "diode",
            "valor",
            "angle",
            "angel",
            "muddy",
            "chase",
            "reply",
            "prone",
            "spoil",
            "heart",
            "shade",
            "diner",
            "diner",
            "onion",
            "sleet",
            "dowel",
            "couch",
            "couch",
            "couch",
            "smile",
            "evoke",
            "evoke",
            "evoke",
            "evoke",
            "evoke",
            "siren",
            "built",
            "embed",
            "award",
            "award",
            "annul",
            "goody",
            "frown",
            "patio",
            "patio",
            "humid",
            "elite",
            "lymph",
            "edify",
            "might",
            "reset",
            "visit",
            "visit",
            "purse",
            "vapor",
            "vapor",
            "write",
            "sunny",
            "loath",
            "loath",
            "slide",
            "slide",
            "venom",
            "stamp",
            "sorry",
            "still",
            "acorn",
            "aping",
            "pushy",
            "tamer",
            "tamer",
            "tamer",
            "awoke",
            "brawn",
            "swift",
            "exile",
            "birch",
            "lucky",
            "freer",
            "freer",
            "ghost",
            "plier",
            "lunar",
            "lunar",
            "snare",
            "nurse",
            "house",
            "borax",
            "nicer",
            "lurch",
            "exalt",
            "about",
            "savvy",
            "toxin",
            "tunic",
            "tunic",
            "inlay",
            "chump",
            "chump",
            "cress",
            "cress",
            "elude",
            "cycle",
            "cycle",
            "boule",
            "moron",
            "tenet",
            "place",
            "lobby",
            "plush",
            "vigil",
            "index",
            "blink",
            "clung",
            "qualm",
            "croup",
            "clink",
            "clink",
            "stage",
            "decay",
            "nerve",
            "flier",
            "flier",
            "crook",
            "clean",
            "clean",
            "ridge",
            "vowel",
            "gnome",
            "snuck",
            "icing",
            "spiny",
            "rigor",
            "snail",
            "flown",
            "flown",
            "prose",
            "thank",
            "poppy",
            "budge",
            "fiber",
            "fiber",
            "dowdy",
            "kneel",
            "track",
            "caddy",
            "quell",
            "quell",
            "paler",
            "paler",
            "rebar",
            "scuba",
            "splat",
            "flyer",
            "flyer",
            "mason",
            "mason",
            "ozone",
            "amply",
            "molar",
            "molar",
            "beset",
            "queue",
            "cliff",
            "magic",
            "truce",
            "sport",
            "fritz",
            "fritz",
            "twirl",
            "verse",
            "llama",
            "eaten",
            "range",
            "whisk",
            "hovel",
            "hovel",
            "macaw",
            "macaw",
            "macaw",
            "verve",
            "sushi",
            "sushi",
            "sushi",
            "brain",
            "brain",
            "brain",
            "brain",
            "candy",
            "chord",
            "basin",
            "march",
            "crowd",
            "arbor",
            "arbor",
            "arbor",
            "arbor",
            "dally",
            "bless",
            "bravo",
            "stung",
            "title",
            "title",
            "kiosk",
            "blond",
            "blond",
            "layer",
            "layer",
            "layer",
            "score",
            "score",
            "zebra",
            "barge",
            "matey",
            "bluer",
            "aider",
            "shook",
            "river",
            "privy",
            "betel",
            "betel",
            "bongo",
            "begun",
            "azure",
            "weave",
            "genie",
            "sound",
            "glove",
            "braid",
            "scope",
            "wryly",
            "rover",
            "assay",
            "ocean",
            "bloom",
            "irate",
            "later",
            "woken",
            "silky",
            "wreck",
            "dwelt",
            "slate",
            "slate",
            "solid",
            "amaze",
            "hazel",
            "wrist",
            "jolly",
            "globe",
            "flint",
            "flint",
            "civil",
            "vista",
            "relax",
            "cover",
            "alive",
            "beech",
            "jetty",
            "bliss",
            "vocal",
            "often",
            "dolly",
            "eight",
            "joker",
            "since",
            "event",
            "ensue",
            "ensue",
            "diver",
            "poser",
            "worst",
            "sweep",
            "alley",
            "alley",
            "alley",
            "leafy",
            "leafy",
            "leafy",
            "stare",
            "stare",
            "waive",
            "choir",
            "stood",
            "spoke",
            "outgo",
            "delay",
            "delay",
            "ideal",
            "ideal",
            "ideal",
            "ideal",
            "laugh",
            "sieve",
            "block",
            "meant",
            "meant",
            "meant",
            "hardy",
            "shied",
            "drawl",
            "daisy",
            "putty",
            "strut",
            "burnt",
            "tulip",
            "crick",
            "idyll",
            "vixen",
            "vixen",
            "geeky",
            "cough",
            "naive",
            "shoal",
            "stork",
            "stork",
            "stork",
            "check",
            "prime",
            "brass",
            "outer",
            "outer",
            "razor",
            "razor",
            "razor",
            "imply",
            "demur",
            "quota",
            "haven",
            "cavil",
            "cavil",
            "cavil",
            "dough",
            "gavel",
            "wagon",
            "salon",
            "nudge",
            "nudge",
            "pitch",
            "sworn",
            "pupil",
            "excel",
            "stony",
            "cabin",
            "cabin",
            "cabin",
            "trout",
            "trout",
            "earth",
            "storm",
            "until",
            "taper",
            "taper",
            "taper",
            "taper",
            "taper",
            "taper",
            "husky",
            "brave",
            "filet",
            "slime",
            "glint",
            "tread",
            "tread",
            "regal",
            "guest",
            "every",
            "murky",
            "share",
            "spore",
            "hoist",
            "buxom",
            "inner",
            "otter",
            "dimly",
            "level",
            "level",
            "donut",
            "stilt",
            "arena",
            "sheet",
            "sheet",
            "fancy",
            "fancy",
            "pearl",
            "silly",
            "porch",
            "porch",
            "sepia",
            "amble",
            "amble",
            "bread",
            "friar",
            "friar",
            "dairy",
            "quill",
            "cross",
            "cross",
            "cross",
            "shear",
            "posit",
            "blank",
            "villa",
            "villa",
            "villa",
            "villa",
            "which",
            "among",
            "among",
            "shell",
            "would",
            "algae",
            "algae",
            "algae",
            "algae",
            "amuse",
            "amuse",
            "copse",
            "copse",
            "copse",
            "pouch",
            "ascot",
            "plane",
            "crown",
            "crown",
            "crown",
            "relay",
            "abide",
            "viola",
            "viola",
            "straw",
            "straw",
            "straw",
            "amass",
            "third",
            "trick",
            "tutor",
            "tutor",
            "blurb",
            "blurb",
            "disco",
            "where",
            "where",
            "beach",
            "beach",
            "comic",
            "clued",
            "clued",
            "clued",
            "graze",
            "graze",
            "graze",
            "graze",
            "graze",
            "graze",
            "lurid",
            "steel",
            "halve",
            "halve",
            "vinyl",
            "utile",
            "utile",
            "adage",
            "worry",
            "worry",
            "local",
            "trade",
            "trade",
            "ashen",
            "modal",
            "gaunt",
            "clove",
            "clove",
            "adorn",
            "roast",
            "speck",
            "speck",
            "speck",
            "grunt",
            "snoop",
            "snoop",
            "party",
            "party",
            "emcee",
            "array",
            "south",
            "vapid",
            "jelly",
            "skulk",
            "angst",
            "tubal",
            "lower",
            "crest",
            "crest",
            "cyber",
            "adore",
            "adore",
            "adore",
            "notch",
            "notch",
            "notch",
            "hitch",
            "hitch",
            "align",
            "ready",
            "frond",
            "frond",
            "puree",
            "realm",
            "venue",
            "swarm",
            "offer",
            "seven",
            "seven",
            "diary",
            "diary",
            "diary",
            "acrid",
            "acrid",
            "theta",
            "junto",
            "pixie",
            "quoth",
            "bonus",
            "shalt",
            "penne",
            "amend",
            "datum",
            "build",
            "piano",
            "shelf",
            "lodge",
            "lodge",
            "rearm",
            "coral",
            "ramen",
            "worth",
            "psalm",
            "infer",
            "overt",
            "mayor",
            "ovoid",
            "glide",
            "usage",
            "poise",
            "poise",
            "poise",
            "prank",
            "fishy",
            "tooth",
            "ether",
            "drove",
            "idler",
            "swath",
            "stint",
            "while",
            "while",
            "apply",
            "apply",
            "tarot",
            "radar",
            "radar",
            "aware",
            "canon",
            "shift",
            "timer",
            "bylaw",
            "serum",
            "three",
            "steak",
            "iliac",
            "iliac",
            "blunt",
            "puppy",
            "puppy",
            "joist",
            "joist",
            "shape",
            "beget",
            "wheel",
            "adept",
            "stunt",
            "stunt",
            "topaz",
            "chore",
            "fluke",
            "afoot",
            "afoot",
            "afoot",
            "dense",
            "caper",
            "caper",
            "boxer",
            "jumbo",
            "lunge",
            "space",
            "avail",
            "short",
            "short",
            "loyal",
            "loyal",
            "pizza",
            "pizza",
            "tempo",
            "tempo",
            "plate",
            "plate",
            "plunk",
            "afoul",
            "savoy",
            "steep",
            "agile",
            "stake",
            "dwell",
            "knave",
            "beard",
            "arose",
            "motif",
            "motif",
            "broil",
            "glare",
            "glare",
            "glare",
            "glare",
            "swamp",
            "along",
            "rugby",
            "wager",
            "wager",
            "wager",
            "snaky",
            "debit",
            "mange",
            "skate",
            "ninth",
            "joust",
            "joust",
            "spurn",
            "medal",
            "medal",
            "medal",
            "medal",
            "learn",
            "nadir",
            "maple",
            "comfy",
            "remit",
            "gruff",
            "ester",
            "least",
            "mogul",
            "fetch",
            "cause",
            "oaken",
            "aglow",
            "aglow",
            "aglow",
            "shyly",
            "racer",
            "prowl",
            "prowl",
            "stern",
            "poesy",
            "poesy",
            "tweet",
            "waist",
            "spire",
            "spire",
            "havoc",
            "patsy",
            "truly",
            "forty",
            "deity",
            "deity",
            "swish",
            "swish",
            "swish",
            "bevel",
            "lemur",
            "draft",
            "draft",
            "draft",
            "lingo",
            "bleak",
            "ditty",
            "ditty",
            "cedar",
            "cedar",
            "grown",
            "grown",
            "grown",
            "grown",
            "crypt",
            "crypt",
            "stock",
            "stock",
            "locus",
            "locus",
            "locus",
            "quite",
            "quite",
            "cache",
            "cache",
            "deign",
            "fiend",
            "logic",
            "cheap",
            "elide",
            "elide",
            "false",
            "false",
            "false",
            "false",
            "false",
            "blaze",
            "envoy",
            "envoy",
            "brief",
            "never",
            "never",
            "mouse",
            "mouse",
            "mouse",
            "fiery",
            "fiery",
            "trunk",
            "trunk",
            "clear",
            "clear",
            "clear",
            "bitty",
            "bitty",
            "koala",
            "duvet",
            "duvet",
            "duvet",
            "super",
            "grill",
            "after",
            "after",
            "ember",
            "ember",
            "nobly",
            "empty",
            "empty",
            "empty",
            "recur",
            "recur",
            "dread",
            "merge",
            "merge",
            "merge",
            "amity",
            "shaky",
            "hover",
            "carol",
            "carol",
            "carol",
            "faint",
            "haunt",
            "flour",
            "chair",
            "chair",
            "chair",
            "chair",
            "plied",
            "quark",
            "quark",
            "novel",
            "novel",
            "stoic",
            "stoic",
            "stoic",
            "stoic",
            "lyric",
            "lyric",
            "lyric",
            "quilt",
            "below",
            "bingo",
            "bingo",
            "bingo",
            "scone",
            "toast",
            "easel",
            "easel",
            "value",
            "value",
            "honor",
            "route",
            "route",
            "route",
            "route",
            "route",
            "phony",
            "issue",
            "issue",
            "issue",
            "issue",
            "issue",
            "issue",
            "flora",
            "flora",
            "latch",
            "wight",
            "wight",
            "retry",
            "holly",
            "decal",
            "decal",
            "decal",
            "decal",
            "decal",
            "defer",
            "defer",
            "optic",
            "optic",
            "vying",
            "vying",
            "vying",
            "vying",
            "shark",
            "shark",
            "shark",
            "bugle",
            "tawny",
            "chalk",
            "feast",
            "feast",
            "pedal",
            "scarf",
            "scarf",
            "bleat",
            "tidal",
            "slush",
            "slush",
            "windy",
            "windy",
            "sally",
            "igloo",
            "igloo",
            "jewel",
            "shone",
            "shone",
            "shone",
            "shone",
            "fugue",
            "elbow",
            "elbow",
            "elbow",
            "elbow",
            "syrup",
            "terse",
            "suave",
            "gamut",
            "gamut",
            "gamut",
            "gamut",
            "afire",
            "shirt",
            "grout",
            "oddly",
            "tithe",
            "plaid",
            "plaid",
            "broom",
            "blind",
            "torch",
            "torch",
            "again",
            "tying",
            "tying",
            "alter",
            "alter",
            "noble",
            "ethos",
            "ethos",
            "extol",
            "decor",
            "hobby",
            "hobby",
            "idiom",
            "utter",
            "these",
            "sixth",
            "alarm",
            "erase",
            "elegy",
            "elegy",
            "elegy",
            "elegy",
            "scold",
            "scold",
            "scold",
            "scold",
            "scold",
            "scold",
            "slash",
            "quake",
            "quake",
            "swept",
            "swept",
            "swept",
            "wield",
            "wield",
            "lasso",
            "maize",
            "shale",
            "shale",
            "shale",
            "smoky",
            "smoky",
            "smoky",
            "glade",
            "spent",
            "prism",
            "stoke",
            "riper",
            "orbit",
            "cocoa",
            "cocoa",
            "humus",
            "shush",
            "table",
            "table",
            "wrong",
            "wrong",
            "alert",
            "shiny",
            "elate",
            "resin",
            "whole",
            "whole",
            "pixel",
            "polar",
            "hotel",
            "hotel",
            "cleat",
            "mango",
            "rumba",
            "rumba",
            "filly",
            "billy",
            "billy",
            "clout",
            "dance",
            "dance",
            "facet",
            "chili",
            "paint",
            "liner",
            "curio",
            "salty",
            "audio",
            "snake",
            "fable",
            "cloak",
            "cloak",
            "cloak",
            "pesto",
            "balmy",
            "balmy",
            "balmy",
            "early",
            "early",
            "early",
            "early",
            "lease",
            "witty",
            "witty",
            "witty",
            "saner",
            "blend",
            "salsa",
            "salsa",
            "salsa",
            "salsa",
            "blare",
            "blare",
            "blare",
            "blare",
            "crepe",
            "knack",
            "knack",
            "debut",
            "debut",
            "haste",
            "haste",
            "agent",
            "agent",
            "icily",
            "icily",
            "ingot",
            "clash",
            "juror",
            "juror",
            "abode",
            "abode",
            "unity",
            "pivot",
            "pivot",
            "pivot",
            "spare",
            "spare",
            "parse",
            "morph",
            "cacti",
            "tacky",
            "spool",
            "spool",
            "moody",
            "moody",
            "begin",
            "begin",
            "begin",
            "water",
            "water",
            "admin",
            "omega",
            "limit",
            "limit",
            "limit",
            "aisle",
            "aisle",
            "basis",
            "basis",
            "verge",
            "botch",
            "botch",
            "lousy",
            "lousy",
            "cubic",
            "raise",
            "wrack",
            "guide",
            "foist",
            "cameo",
            "cameo",
            "cameo",
            "revue",
            "revue",
            "harpy",
            "scoop",
            "climb",
            "refer",
            "olden",
            "clerk",
            "debar",
            "tally",
            "ethic",
            "cairn",
            "tulle",
            "ghoul",
            "hilly",
            "hilly",
            "apart",
            "scale",
            "scale",
            "plain",
            "plain",
            "plain",
            "plain",
            "rerun",
            "quest",
            "crisp",
            "crisp",
            "befit",
            "drawn",
            "suite",
            "suite",
            "cheer",
            "bagel",
            "guess",
            "guess",
            "axiom",
            "axiom",
            "caput",
            "leant",
            "harsh",
            "harsh",
            "proud",
            "swing",
            "opine",
            "opine",
            "opine",
            "gumbo",
            "miner",
            "green",
            "green",
            "lipid",
            "topic",
            "armor",
            "brush",
            "crane",
            "mural",
            "abled",
            "habit",
            "habit",
            "maker",
            "dusky",
            "dizzy",
            "dizzy",
            "brook",
            "jazzy",
            "fifty",
            "sense",
            "sense",
            "sense",
            "sense",
            "sense",
            "flunk",
            "began",
            "prune",
            "small",
            "small",
            "scoff",
            "torus",
            "torus",
            "torus",
            "viper",
            "taken",
            "taken",
            "vogue",
            "owing",
            "owing",
            "owing",
            "booth",
            "booth",
            "chide",
            "chide",
            "chide",
            "neigh",
            "minim",
            "minim",
            "kneed",
            "decoy",
            "voila",
            "ankle",
            "arrow",
            "arrow",
            "arrow",
            "cease",
            "eager",
            "eager",
            "graph",
            "odder",
            "terra",
            "terra",
            "tried",
            "clack",
            "color",
            "color",
            "weigh",
            "weigh",
            "ladle",
            "ladle",
            "craft",
            "minus",
            "minus",
            "titan",
            "lucid",
            "lucid",
            "lucid",
            "lucid",
            "lucid",
            "pasta",
            "taffy",
            "flame",
            "swoop",
            "aloof",
            "sight",
            "sight",
            "teary",
            "chart",
            "sixty",
            "wordy",
            "sheer",
            "sheer",
            "sheer",
            "sheer",
            "savor",
            "clamp",
            "clamp",
            "clamp",
            "clamp",
            "brand",
            "brand",
            "dingy",
            "butte",
            "drill",
            "tripe",
            "bicep",
            "tenor",
            "krill",
            "worse",
            "drama",
            "hyena",
            "think",
            "think",
            "cobra",
            "basil",
            "scrum",
            "bused",
            "phone",
            "court",
            "court",
            "proof",
            "heard",
            "angel",
            "angel",
            "angel",
            "angel",
            "maybe",
            "maybe",
            "sprig",
            "spine",
            "shout",
            "cadet",
            "macro",
            "macro",
            "satyr",
            "rarer",
            "binge",
            "trend",
            "trend",
            "leapt",
            "amiss",
            "split",
            "myrrh",
            "width",
            "sonar",
            "sonar",
            "baron",
            "fever",
            "waver",
            "spark",
            "belie",
            "sloop",
            "sloop",
            "smote",
            "baler",
            "above",
            "north",
            "wafer",
            "scant",
            "frill",
            "awash",
            "snack",
            "scowl",
            "frail",
            "drift",
            "limbo",
            "fence",
            "motel",
            "motel",
            "wreak",
            "revel",
            "talon",
            "prior",
            "prior",
            "cello",
            "cello",
            "debug",
            "anode",
            "anode",
            "salve",
            "scout",
            "imbue",
            "imbue",
            "stave",
            "vague",
            "chock",
            "fight",
            "video",
            "stone",
            "teach",
            "cleft",
            "frost",
            "frost",
            "frost",
            "frost",
            "apnea",
            "apnea",
            "plaza",
            "ledge",
            "tweak",
            "board",
            "grant",
            "medic",
            "medic",
            "cable",
            "brawl",
            "slunk",
            "slunk",
            "forum",
            "drone",
            "drone",
            "drone",
            "boast",
            "boast",
            "coven",
            "coven",
            "truer",
            "wrath",
            "stall",
            "steam",
            "axial",
            "axial",
            "daily",
            "trail",
            "niche",
            "mealy",
            "mealy",
            "nylon",
            "nylon",
            "merry",
            "flail",
            "flail",
            "wheat",
            "berry",
            "cower",
            "cower",
            "brute",
            "brute",
            "brute",
            "sinew",
            "skier",
            "penny",
            "jumpy",
            "rally",
            "umbra",
            "scary",
            "modem",
            "modem",
            "avian",
            "greed",
            "satin",
            "tonic",
            "parka",
            "parka",
            "livid",
            "livid",
            "livid",
            "giddy",
            "reuse",
            "reuse",
            "avoid",
            "quote",
            "quote",
            "liken",
            "gloss",
            "gloss",
            "beret",
            "noise",
            "noise",
            "dealt",
            "dealt",
            "rumor",
            "opera",
            "opera",
            "tonga",
            "flare",
            "flare",
            "flare",
            "flare",
            "etude",
            "etude",
            "circa",
            "circa",
            "inbox",
            "inbox",
            "grain",
            "exert",
            "exert",
            "exert",
            "belle",
            "salvo",
            "salvo",
            "fruit",
            "fruit",
            "fruit",
            "fruit",
            "ovine",
            "spiky",
            "frank",
            "frank",
            "frank",
            "frank",
            "heave",
            "mambo",
            "right",
            "clank",
            "trust",
            "lumen",
            "borne",
            "borne",
            "borne",
            "amber",
            "lathe",
            "carat",
            "corer",
            "corer",
            "corer",
            "affix",
            "alloy",
            "alloy",
            "sheep",
            "sheep",
            "wooly",
            "mauve",
            "flung",
            "yacht",
            "fried",
            "quail",
            "brunt",
            "brunt",
            "brunt",
            "brunt",
            "rinse",
            "rinse",
            "state",
            "state",
            "state",
            "bison",
            "graft",
            "graft",
            "baste",
            "flask",
            "hedge",
            "hedge",
            "swash",
            "swash",
            "coupe",
            "coupe",
            "abhor",
            "abhor",
            "abhor",
            "abhor",
            "geese",
            "miser",
            "mirth",
            "cloud",
            "cabal",
            "cabal",
            "close",
            "tenth",
            "pecan",
            "droit",
            "grail",
            "clone",
            "guise",
            "ralph",
            "tango",
            "biddy",
            "smith",
            "mower",
            "payee",
            "serif",
            "serif",
            "fifth",
            "fifth",
            "glaze",
            "allot",
            "allot",
            "kayak",
            "kayak",
            "testy",
            "testy",
            "fully",
            "zonal",
            "metro",
            "metro",
            "grand",
            "banjo",
            "axion",
            "bezel",
            "occur",
            "chain",
            "chain",
            "chain",
            "filer",
            "brace",
            "allay",
            "allay",
            "raven",
            "plead",
            "gnash",
            "flaky",
            "munch",
            "dully",
            "dully",
            "thing",
            "slink",
            "hurry",
            "hurry",
            "shorn",
            "shorn",
            "ranch",
            "wring",
            "lemon",
            "shore",
            "shore",
            "froze",
            "newer",
            "style",
            "moose",
            "antic",
            "antic",
            "antic",
            "chess",
            "guppy",
            "union",
            "lever",
            "lorry",
            "image",
            "cabby",
            "druid",
            "exact",
            "truth",
            "truth",
            "spool",
            "cried",
            "chime",
            "crony",
            "crony",
            "timid",
            "batch",
            "gauge",
            "rotor",
            "rotor",
            "curve",
            "latte",
            "witch",
            "bunch",
            "repel",
            "anvil",
            "anvil",
            "meter",
            "broth",
            "madly",
            "dried",
            "scene",
            "known",
            "magma",
            "roost",
            "roost",
            "roost",
            "roost",
            "pasty",
            "pasty",
            "knead",
            "whirl",
            "rapid",
            "clang",
            "anger",
            "drive",
            "goofy",
            "email",
            "music",
            "stuff",
            "bleep",
            "bleep",
            "bleep",
            "folio",
            "setup",
            "verso",
            "quash",
            "fauna",
            "fauna",
            "happy",
            "newly",
            "fussy",
            "relic",
            "guava",
            "guava",
            "fudge",
            "femur",
            "chirp",
            "forte",
            "alibi",
            "whine",
            "whine",
            "golly",
            "plait",
            "fleck",
            "felon",
            "gourd",
            "gourd",
            "thrum",
            "ficus",
            "ficus",
            "decry",
            "wiser",
            "junta",
            "visor",
            "daunt",
            "scree",
            "impel",
            "await",
            "press",
            "whose",
            "turbo",
            "stoop",
            "speak",
            "speak",
            "eying",
            "inlet",
            "crone",
            "pulse",
            "mossy",
            "staid",
            "hence",
            "pinch",
            "pinch",
            "sully",
            "snore",
            "ripen",
            "snowy",
            "attic",
            "going",
            "leach",
            "leach",
            "hound",
            "clump",
            "tonal",
            "tonal",
            "peril",
            "piece",
            "blame",
            "haute",
            "spied",
            "undid",
            "intro",
            "basal",
            "shine",
            "gecko",
            "rodeo",
            "guard",
            "steer",
            "steer",
            "scamp",
            "scram",
            "scram",
            "hello",
            "vaunt",
            "vaunt",
            "vaunt",
            "knock",
            "extra",
            "condo",
            "adapt",
            "adapt",
            "polka",
            "rayon",
            "rayon",
            "faith",
            "faith",
            "match",
            "mercy",
            "tepid",
            "sleek",
            "riser",
            "twixt",
            "peace",
            "peace",
            "catty",
            "login",
            "eject",
            "eject",
            "rival",
            "untie",
            "refit",
            "aorta",
            "aorta",
            "judge",
            "rower",
            "artsy",
            "rural",
            "rural",
        ];

        this.alphabet = [
            [
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
            ],
            [
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
            ],
            [
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
            ],
            [
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]
            ],
            [
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
            ],
            [
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
            ],
            [
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
            ],
            [
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
            ],
            [
                [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0]
            ],
            [
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
            ],
            [
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0]
            ],
            [
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
            ],
            [
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
            ],
            [
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
            ],
            [
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
            ],
            [
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
            ],
            [
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0]
            ],
            [
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0]
            ],
            [
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
            ],
            [
                [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
            ],
            [
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0]
            ],
            [
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0]
            ],
            [
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
            ],
            [
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0]
            ],
            [
                [0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
                [0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
                [0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
                [0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
                [0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
                [0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
                [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
                [0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0]
            ],
            [
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0],
                [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
                [0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0],
                [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]
            ]
        ];


        this.GREEN = [0, 255, 0]; // #6aaa64 : 106, 170, 100
        this.YELLOW = [255, 255, 0]; // #c9b458 : 201, 180, 88
        this.GRAY = [255, 255, 255];  // #787c7e : 120, 124, 126

        this.reverseAnimation = false;

        this.GAME_PLAYING = 0;
        this.GAME_LOST = 1
        this.GAME_WON = 2;

        this.dayOffset;
        this.answer;

        this.guesses = [];
        this.triesAllowed = 4;
        this.tryCount = 0;
        this.gameState = this.GAME_PLAYING;

        this.display = display;

        this.AUTO = true;

        this.startGame();
    }

    //Gives days since start date
    #daysSince(startDate) {
        return Math.floor(
            (new Date() - new Date(startDate)) / (1000 * 3600 * 24)
        );
    }

    //Run to start a new game
    startGame() {
        this.guesses = [];
        this.tryCount = 0;
        this.gameState = this.GAME_PLAYING;

        this.reverseAnimation = false;

        if (this.AUTO) {
            this.answer = this.dailyAnswers[Math.floor(Math.random() * this.dailyAnswers.length)];
        } else {
            let dayOffset = this.#daysSince("2022-11-04T00:00:00.000");
            console.log("dayOffset: " + dayOffset);

            this.answer = this.dailyAnswers[(516 + dayOffset) % this.dailyAnswers.length];
        }

        console.log("Word: " + this.answer);

        for (let i = 0; i < this.triesAllowed; i++) {
            let guess = {
                word: "#####",
                colors: [this.GRAY, this.GRAY, this.GRAY, this.GRAY, this.GRAY],
                animationPercentages: [0, 0, 0, 0, 0]
            };

            this.guesses.push(JSON.parse(JSON.stringify(guess)));
        }

        if (this.AUTO) {
            this.#tryAutoGuess(true);
        }
    }

    //The point of interaction for the class, this is called by the user
    guess(word) {
        let response;

        if (this.gameState == this.GAME_LOST) {
            return "FAIL: Game already lost";
        }

        if (this.gameState == this.GAME_WON) {
            return "FAIL: Game already won";
        }

        if (this.dailyAnswers.indexOf(word.toLowerCase()) == -1) {
            return "FAIL: Word not allowed";
        }

        for (let guess of this.guesses) {
            if (guess.word == word) {
                return "FAIL: Word already guessed";
            }
        }

        this.#addGuess(word);

        if (word == this.answer) {
            return "SUCCESS: Game won";
        }

        return "SUCCESS: Guess accepted";
    }

    // Repeatedly try to automatically guess words until the game is won or lost waiting between guesses
    #tryAutoGuess(instant = false) {
        clearInterval(this.autoGuessInterval);
        this.autoGuessInterval = setTimeout(() => {
            if (this.gameState == this.GAME_PLAYING) {
                this.#autoGuess();
                clearInterval(this.autoGuessInterval);
                this.autoGuessInterval = this.#tryAutoGuess();
            }
        }, (instant) ? 1 : (Math.random() * 3000) + 4000);
    }

    // Score a guess, add it to guesses and update game states
    #addGuess(word) {
        let guess = this.#scoreGuess(word);
        console.log("Guess: " + word);
        this.guesses[this.tryCount] = guess;

        this.tryCount++;

        if (this.gameState == this.GAME_PLAYING) {
            if (this.tryCount >= this.triesAllowed) {
                this.gameState = this.GAME_LOST;

                setTimeout(() => {this.startGame();}, 8000); //Schedule a new game to start 
                setTimeout(() => {this.reverseAnimation = true;}, 7000);
            }
        }

        if (word == this.answer) {
            this.gameState = this.GAME_WON;

            setTimeout(() => {this.startGame();}, 8000); //Schedule a new game to start
            setTimeout(() => {this.reverseAnimation = true;}, 7000);
        }
    }

    // Create a guess object for a word
    #scoreGuess(word, answer = this.answer) {
        let tempAnswer = answer.split("");

        let guess = {
            word: word,
            colors: [this.GRAY, this.GRAY, this.GRAY, this.GRAY, this.GRAY],
            animationPercentages: [0, 0, 0, 0, 0]
        };

        //Do all greens first 
        for (let i = 0; i < 5; i++) {
            if (word[i] == tempAnswer[i]) {
                guess.colors[i] = this.GREEN;
                tempAnswer[i] = "#"; //Remove the character from the answer so it won't be seen as yellow
            }
        }

        for (let i = 0; i < 5; i++) {
            if (tempAnswer[i] == "#") {
                continue; //Skip this character if it was already used as a green
            }

            let position = tempAnswer.indexOf(word[i]);
            if (position != -1) {
                guess.colors[i] = this.YELLOW;
                tempAnswer[position] = "#"; //Remove that character from the answer so it won't be seen as yellow again
            }
        }

        return guess;
    }

    //Flip letter animation 
    #revealGuess() {
        for (let guess of this.guesses) {
            if (guess.word != "#####") {

                if (this.reverseAnimation) {
                    for (let i = 0; i < 5; i++) {
                        guess.animationPercentages[i] = Math.max(0, guess.animationPercentages[i] - 0.1);
                    }

                } else {
                    // One at a time
                    let i = 0;
                    while (guess.animationPercentages[i] == 1) {
                        i++;
                    }
                    if (i > guess.animationPercentages.length) {
                        return;
                    }

                    guess.animationPercentages[i] = Math.min(guess.animationPercentages[i] + 0.1, 1);
                }
            }
        }
    }

    #autoGuess() {
        // Guess randomly if no guesses have been made
        if (this.tryCount == 0) {
            this.#addGuess(this.dailyAnswers[Math.floor(Math.random() * this.dailyAnswers.length)]);
            return;
        }

        let letterBlacklist = {};
        let letterWhitelist = {};

        for (let i = 0; i < this.tryCount; i++) {
            let guess = this.guesses[i];

            for (let j = 0; j < guess.word.length; j++) {
                // Find the list of letters that can't be in the answer
                if (guess.colors[j] == this.GRAY) {
                    // Only blacklist if it's really not in the word (not just gray because it's a double letter with a green already)
                    if (this.answer.indexOf(guess.word[j]) == -1) {
                        // Mark letter as blacklisted in all positions
                        letterBlacklist[guess.word[j]] = [...Array(this.answer.length).keys()];
                    }
                }

                if (guess.colors[j] == this.YELLOW) {
                    // Mark letter as blacklisted in the current position
                    if (letterBlacklist[guess.word[j]] == undefined) {
                        letterBlacklist[guess.word[j]] = [j];
                    } else {
                        if (letterBlacklist[guess.word[j]].indexOf(j) == -1) {
                            letterBlacklist[guess.word[j]].push(j);
                        }
                    }

                    // Mark letter as whitelisted in all other positions
                    letterWhitelist[guess.word[j]] = [...Array(this.answer.length).keys()];
                    letterWhitelist[guess.word[j]].splice(j, 1);
                }

                // Find the list of letters that must be in the answer
                if (guess.colors[j] == this.GREEN) {
                    letterWhitelist[guess.word[j]] = [j];
                }
            }
        }

        //Find the list of remaining possibilities given the blacklisted and whitelisted letters
        let possibleWords = [];
        for (let word of this.dailyAnswers) {
            let possible = true;
            for (let letter in letterBlacklist) {
                // If the word contains a letter in a blacklisted position, it is not possible
                for (let position of letterBlacklist[letter]) {
                    if (word[position] == letter) {
                        possible = false;
                        break;
                    }
                }
            }

            // For every word, every letter of whitelist, if the word doesn't contain the letter, in any of the listed positions, it is not possible
            for (let letter in letterWhitelist) {
                let any = false;
                for (let position of letterWhitelist[letter]) {
                    if (word[position] == letter) {
                        any = true;
                        break;
                    }
                }

                if (!any) {
                    possible = false;
                    break;
                }
            }

            if (possible) {
                possibleWords.push(word);
            }
        }

        //Find the number of answers that contain each letter that isn't blacklisted
        let letterCounts = {};
        for (let word of possibleWords) {
            for (let letter of word) {
                if (letterBlacklist[letter] == undefined) {
                    if (letterCounts[letter] == undefined) {
                        letterCounts[letter] = 1;
                    } else {
                        letterCounts[letter]++;
                    }
                }
            }
        }

        let letterTotal = 0;
        for (let letter in letterCounts) {
            letterTotal += letterCounts[letter];
        }

        //Find the word that divides the possible words in half the most evenly
        console.log("Possible words: " + possibleWords.length);
        let bestWord = possibleWords[0];
        let bestScore = 999999999999;
        for (let word of possibleWords) {

            let alreadyGuessed = false;
            for (let guess of this.guesses) {
                if (guess.word == word) {
                    alreadyGuessed = true;
                    break;
                }
            }
            if (alreadyGuessed) {
                continue;
            }

            let score = 0;
            for (let letter of word) {
                score += letterCounts[letter];
            }
            if (Math.abs(score - (letterTotal / 2)) < bestScore) {
                bestWord = word;
                bestScore = score;
            }
        }

        //console.log(letterBlacklist);
        //console.log(letterWhitelist);

        console.assert(bestWord != undefined, "No best word found");
        this.#addGuess(bestWord);
    }

    #drawLetter(letter, xpos, ypos) {
        let letterData = this.alphabet[letter.toLowerCase().charCodeAt(0) - 97];

        for (let y = 0; y < letterData.length; y++) {
            for (let x = 0; x < letterData[y].length; x++) {
                if (letterData[y][x]) {
                    this.display.setPixel(
                        Math.min(
                            Math.max(0, xpos + x),
                            this.display.width - 1
                        ),
                        Math.min(
                            Math.max(0, ypos + y),
                            this.display.height - 1
                        ),
                        [0, 0, 0]);
                }
            }
        }
    }

    #drawTile(letter, xpos, ypos, color, animationPercentage) {
        let height = Math.cos(animationPercentage * Math.PI); //Tile flip rotation

        let tileSize = 18;
        let halfTileSize = Math.floor(tileSize / 2);

        // Front face of tile before animation complete
        let drawColor = color;
        if (animationPercentage < 0.5) {
            drawColor = this.GRAY;
        }

        for (let y = 0; y < tileSize; y++) {
            if (Math.abs(y - halfTileSize) / halfTileSize < Math.abs(height)) {
                for (let x = 0; x < tileSize; x++) {
                    this.display.setPixel(
                        Math.min(
                            Math.max(0, xpos + x),
                            this.display.width - 1
                        ),
                        Math.min(
                            Math.max(0, ypos + y),
                            this.display.height - 1
                        ),
                        drawColor);
                }
            }
        }

        if (animationPercentage >= 0.93) {
            this.#drawLetter(letter, xpos + 2, ypos + 2);
        }
    }

    #drawGuess(guess, xpos, ypos) {
        let tileSpacing = 20;

        for (let i = 0; i < 5; i++) {
            this.#drawTile(guess.word[i], xpos + (i * tileSpacing), ypos, guess.colors[i], guess.animationPercentages[i]);
        }
    }


    #drawGuesses() {
        let rowSpacing = 20;

        for (let i = 0; i < this.guesses.length; i++) {
            this.#drawGuess(this.guesses[i], 12, 1 + (i * rowSpacing));
        }
    }

    update() {
        this.#clear();

        this.#revealGuess();
        this.#drawGuesses();

        this.display.flush();
    }

    #clear() {
        for (let x = 0; x < this.display.width; x++) {
            for (let y = 0; y < this.display.height; y++) {
                this.display.setPixel(x, y, [0, 0, 0]);
            }
        }
    }
}
